name: Build Light Theme

on:
  schedule:
    - cron: "0 0 1/5 * *"

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: pip install
        run: pip install -r requirements.txt
      - name: Execute script
        run: |
          python updateMissionIconLinks.py
        working-directory: script
      - name: Comit build
        run: |
          git add .
          git config --global user.name 'TheKeineAhnung'
          git config --global user.email 'kontakt@keineahnung.eu'
          git checkout main
          git commit -m "✨ new missionicon links"
          git push origin main
